type LegalLocale = 'en' | 'es';

export interface LegalSection {
  id: string;
  title: string;
  label: string;
  body?: string[];
  bullets?: string[];
}

export const LEGAL_OPERATOR = {
  name: 'Adrian Obed Rojas Holdings LLC',
  brand: 'Ownward Hub',
  address: '5900 Balcones Drive STE 100, Austin, TX 78731',
  email: 'ownwardhub@gmail.com',
} as const;

export const TERMS_CONTENT: Record<LegalLocale, { badge: string; title: string; note: string; sections: LegalSection[] }> = {
  en: {
    badge: 'Terms of Service',
    title: 'Ownward Hub Terms of Service',
    note: 'These terms explain the current rules for using Ownward Hub. Ownward may update them as the platform introduces new services, marketplace features, subscriptions, integrations, or transaction tools. When a material change affects users\' rights or responsibilities, Ownward will provide notice through the platform, by email, or through another appropriate method.',
    sections: [
      { id: 'acceptance', label: '1. Acceptance', title: '1. Acceptance of the Terms', body: ['By using Ownward Hub, you agree to these Terms. If you use Ownward for an organization, you confirm authority to bind that organization.'] },
      { id: 'operator', label: '2. Operator', title: '2. Service Operator and Contact', body: [`Ownward Hub is operated by ${LEGAL_OPERATOR.name}, a Texas limited liability company. Correspondence address (not a walk-in location): ${LEGAL_OPERATOR.address}. Contact: ${LEGAL_OPERATOR.email}.`] },
      { id: 'eligibility', label: '3. Eligibility', title: '3. Eligibility, 18+ Requirement, and Business Authority', body: ['The Services are intended for adults 18+. You must provide accurate information and have authority to act for any business account you create or manage.'] },
      { id: 'accounts', label: '4. Accounts', title: '4. Accounts, Credentials, and Security', body: ['You are responsible for account credentials and activity under your account. Notify us promptly of unauthorized access or security concerns.'] },
      { id: 'services', label: '5. Services', title: '5. Description of the Services', bullets: ['Ownward is a software, marketplace, organizational, educational, and communication platform.', 'Features include business workspaces, listings, messaging, documents, bookkeeping, valuation tools, CRM workflows, support, and deal-room collaboration.'] },
      { id: 'plans', label: '6. Plans', title: '6. Free and Paid Plans', body: ['Features and limits vary by plan. Checkout and in-product plan displays control current pricing and included limits.'] },
      { id: 'subscriptions', label: '7. Subscriptions', title: '7. Subscriptions, Renewal, Billing, Cancellation, Upgrades, and Downgrades', bullets: ['Paid subscriptions are billed monthly unless checkout states otherwise.', 'Subscriptions automatically renew until canceled.', 'Manage or cancel through the Stripe Customer Portal.', 'Cancellation typically takes effect at the end of the current paid period; cancel before renewal to avoid the next charge.', 'Failed or reversed payments may restrict or suspend paid features.', 'Prices, features, and limits may change with notice; taxes may apply.', 'Downgrades can reduce limits for businesses, documents, storage, leads, collaborators, deal rooms, and related features. Content over new limits may become read-only or blocked from new uploads/creates until reduced; Ownward does not silently delete content solely due to downgrade.'] },
      { id: 'refunds', label: '8. Refunds', title: '8. Refund Policy', body: ['Fees already paid are generally not prorated or refunded unless required by law or expressly stated in checkout or a written offer.'] },
      { id: 'one-time', label: '9. One-time Services', title: '9. One-Time Paid Services (including Featured Listings)', bullets: ['Featured Listings are one-time promotional purchases unless checkout expressly states recurring billing.', 'Ownward does not guarantee views, inquiries, offers, financing, or sale outcomes from Featured Listings.'] },
      { id: 'marketplace-role', label: '10. Marketplace Role', title: '10. Marketplace Role and Limitations', body: ['Ownward is not a buyer or seller in marketplace transactions and does not act as escrow agent or transaction counterparty.'] },
      { id: 'seller', label: '11. Seller Duties', title: '11. Seller Responsibilities and Listing Accuracy', body: ['Sellers are responsible for lawful listing content, truthful disclosures, and permissions for information submitted.'] },
      { id: 'buyer', label: '12. Buyer Duties', title: '12. Buyer Responsibilities, Verification, and Due Diligence', body: ['Buyers are responsible for independent verification and due diligence before any transaction decision.'] },
      { id: 'tools-disclaimer', label: '13. Professional Disclaimers', title: '13. Valuations, Scores, Bookkeeping, Analytics, Academy, and Professional-Advice Disclaimers', bullets: ['Tools and outputs are informational only.', 'Ownward is not a broker, investment adviser, securities broker, lender, law firm, accounting firm, tax adviser, valuation professional, insurance adviser, or escrow provider.', 'Nothing in Ownward replaces legal, tax, accounting, valuation, lending, insurance, cybersecurity, or investment professionals.'] },
      { id: 'messages', label: '14. Messages', title: '14. Messages and User Interactions', body: ['Users are responsible for communications sent through the platform. Abuse, harassment, fraud, and unlawful content are prohibited.'] },
      { id: 'deal-rooms', label: '15. Deal Rooms', title: '15. Deal Rooms, Confidential Information, Participant Access, NDAs, Downloads, and Activity Logs', bullets: ['Deal rooms provide shared workspace controls, requests, files, and activity logs.', 'Providing a deal room does not itself create an NDA; users must obtain their own confidentiality and transaction agreements.', 'Authorized participants may view, download, retain, and further process information they can access.'] },
      { id: 'user-content', label: '16. User Content', title: '16. User Content, Ownership, and Limited Platform License', body: ['You retain ownership of your content and grant Ownward a limited license to host, process, display, and transmit it to operate, secure, and support the Services.'] },
      { id: 'public-v-private', label: '17. Visibility', title: '17. Public Listings vs. Private Workspace Content', body: ['Published listings are public. Drafts and private workspace/deal-room content are restricted to authorized access paths, but participants who can access content may retain copies.'] },
      { id: 'third-party-data', label: '18. Third-Party Data', title: '18. Third-Party and Customer Data Uploaded by Users', body: ['You must have lawful authority before uploading data about other people. Redact unnecessary sensitive identifiers before upload.'] },
      { id: 'prohibited', label: '19. Prohibited Conduct', title: '19. Prohibited Conduct and Restricted Data', bullets: ['No unlawful, fraudulent, infringing, abusive, or security-harming behavior.', 'Do not upload passwords, authentication secrets, full payment-card data, full bank credentials, Social Security numbers, or government ID numbers unless strictly necessary and lawfully handled.'] },
      { id: 'ip', label: '20. IP', title: '20. Intellectual Property', body: ['Ownward software, branding, and site content are protected by intellectual property laws. These Terms do not transfer ownership rights to users.'] },
      { id: 'third-party-services', label: '21. Providers', title: '21. Third-Party Services (Stripe, Supabase, Vercel)', bullets: ['Supabase supports authentication, database, and file storage.', 'Stripe supports checkout, subscription management, payment processing, and billing records.', 'Vercel supports hosting and consent-controlled analytics.'] },
      { id: 'availability', label: '22. Availability', title: '22. Service Availability, Beta Features, Modifications, and Discontinuation', body: ['Services may change, be interrupted, or be discontinued. Beta or preview features may have additional instability and limits.'] },
      { id: 'suspension', label: '23. Suspension', title: '23. Suspension, Termination, Cancellation, and Data Consequences', body: ['We may suspend or terminate accounts for abuse, legal compliance, security, or nonpayment. You may cancel according to your plan terms.'] },
      { id: 'warranty', label: '24. Warranties', title: '24. Disclaimer of Warranties', body: ['Services are provided “as is” and “as available.” Ownward does not guarantee listing accuracy, user identities, documents, valuations, financing, transaction outcomes, or platform availability.'] },
      { id: 'liability', label: '25. Liability', title: '25. Limitation of Liability', body: ['To the extent permitted by law, Ownward is not liable for indirect, incidental, special, consequential, or punitive damages arising from use of the Services.'] },
      { id: 'indemnity', label: '26. Indemnification', title: '26. Indemnification', body: ['You agree to defend and indemnify Ownward from claims arising from your content, conduct, violations of law, or violations of these Terms.'] },
      { id: 'law', label: '27. Governing Law', title: '27. Governing Law and Venue', body: ['Texas law governs these Terms, subject to mandatory consumer law. Venue: state courts in Travis County, Texas, or the U.S. District Court for the Western District of Texas, Austin Division. No mandatory arbitration or class-action waiver is imposed by these Terms.'] },
      { id: 'changes', label: '28. Changes', title: '28. Changes to the Terms and Notice of Material Changes', body: ['We may update Terms. Material updates may require affirmative re-acceptance before continued use of authenticated tools. Any future transaction/referral/success fee requires separate clear disclosure and acceptance before charge.'] },
      { id: 'contact', label: '29. Contact', title: '29. Contact Information', body: [`Contact ${LEGAL_OPERATOR.brand} at ${LEGAL_OPERATOR.email}.`] },
    ],
  },
  es: {
    badge: 'Términos del servicio',
    title: 'Términos del servicio de Ownward Hub',
    note: 'Estos términos explican las reglas actuales para usar Ownward Hub. Ownward puede actualizarlos a medida que la plataforma introduzca nuevos servicios, funciones del mercado, suscripciones, integraciones o herramientas de transacción. Cuando un cambio material afecte los derechos o responsabilidades de los usuarios, Ownward proporcionará aviso a través de la plataforma, por correo electrónico u otro método apropiado.',
    sections: [
      { id: 'acceptance', label: '1. Aceptación', title: '1. Aceptación de los Términos', body: ['Al usar Ownward Hub aceptas estos Términos. Si actúas por una organización, confirmas que tienes autoridad para obligarla.'] },
      { id: 'operator', label: '2. Operador', title: '2. Operador del servicio y contacto', body: [`Ownward Hub es operado por ${LEGAL_OPERATOR.name}, una LLC de Texas. Dirección de correspondencia (no atención presencial): ${LEGAL_OPERATOR.address}. Contacto: ${LEGAL_OPERATOR.email}.`] },
      { id: 'eligibility', label: '3. Elegibilidad', title: '3. Elegibilidad, requisito de 18+ y autoridad empresarial', body: ['El servicio está dirigido a adultos de 18 años o más. Debes proporcionar datos correctos y tener autoridad para cualquier cuenta empresarial.'] },
      { id: 'accounts', label: '4. Cuentas', title: '4. Cuentas, credenciales y seguridad', body: ['Eres responsable de tus credenciales y de la actividad de tu cuenta. Avísanos de inmediato sobre accesos no autorizados.'] },
      { id: 'services', label: '5. Servicios', title: '5. Descripción de los servicios', bullets: ['Ownward es una plataforma de software, marketplace, organización, educación y comunicación.', 'Incluye espacios de trabajo, publicaciones, mensajería, documentos, contabilidad, valoración, CRM, soporte y colaboración en deal rooms.'] },
      { id: 'plans', label: '6. Planes', title: '6. Planes gratuitos y de pago', body: ['Las funciones y límites varían por plan. El checkout y las pantallas del producto controlan el precio y límites vigentes.'] },
      { id: 'subscriptions', label: '7. Suscripciones', title: '7. Suscripciones, renovación, cobro, cancelación, mejoras y cambios de plan', bullets: ['Los planes de pago se cobran mensualmente salvo que el checkout indique otra cosa.', 'La suscripción se renueva automáticamente hasta cancelar.', 'Puedes gestionar/cancelar en Stripe Customer Portal.', 'La cancelación normalmente aplica al final del período pagado; cancela antes de renovar para evitar el próximo cobro.', 'Pagos fallidos o revertidos pueden restringir funciones de pago.', 'Precios, funciones y límites pueden cambiar con aviso; pueden aplicar impuestos.', 'Al bajar de plan pueden reducirse límites (negocios, documentos, almacenamiento, leads, colaboradores, deal rooms y funciones). El contenido sobre límite puede quedar solo lectura o bloqueado para nuevas cargas/creaciones hasta ajustarse; Ownward no elimina silenciosamente contenido solo por downgrade.'] },
      { id: 'refunds', label: '8. Reembolsos', title: '8. Política de reembolsos', body: ['Generalmente no hay prorrateos ni reembolsos de pagos ya realizados, salvo exigencia legal o indicación expresa en checkout/oferta escrita.'] },
      { id: 'one-time', label: '9. Pago único', title: '9. Servicios de pago único (incluyendo Featured Listings)', bullets: ['Featured Listings es una compra promocional de pago único salvo que checkout indique recurrencia.', 'Ownward no garantiza vistas, contactos, ofertas, financiamiento ni cierre de venta por Featured Listings.'] },
      { id: 'marketplace-role', label: '10. Rol del marketplace', title: '10. Rol y límites del marketplace', body: ['Ownward no es comprador ni vendedor en transacciones del marketplace ni actúa como contraparte o agente de escrow.'] },
      { id: 'seller', label: '11. Obligaciones del vendedor', title: '11. Responsabilidades del vendedor y exactitud de la publicación', body: ['El vendedor responde por la legalidad y veracidad del contenido y por tener permisos para la información compartida.'] },
      { id: 'buyer', label: '12. Obligaciones del comprador', title: '12. Responsabilidades del comprador, verificación y debida diligencia', body: ['El comprador es responsable de su verificación independiente y debida diligencia antes de decisiones de transacción.'] },
      { id: 'tools-disclaimer', label: '13. Descargos profesionales', title: '13. Valoraciones, puntajes, contabilidad, analítica, Academia y descargos de asesoría profesional', bullets: ['Las herramientas y resultados son informativos.', 'Ownward no es corredor, asesor de inversión, broker de valores, prestamista, firma legal, firma contable, asesor fiscal, valuador profesional, asesor de seguros ni proveedor de escrow.', 'Nada en Ownward sustituye asesoría legal, fiscal, contable, de valoración, crédito, seguros, ciberseguridad o inversión.'] },
      { id: 'messages', label: '14. Mensajes', title: '14. Mensajes e interacciones entre usuarios', body: ['Cada usuario es responsable por sus comunicaciones. Está prohibido el abuso, fraude, acoso o contenido ilegal.'] },
      { id: 'deal-rooms', label: '15. Deal rooms', title: '15. Deal rooms, información confidencial, acceso, NDAs, descargas y bitácoras', bullets: ['Los deal rooms ofrecen controles de colaboración, solicitudes, archivos y bitácoras de actividad.', 'Un deal room por sí solo no crea un NDA; los usuarios deben obtener sus acuerdos de confidencialidad y transacción.', 'Participantes autorizados pueden ver, descargar, retener y procesar información a la que tengan acceso.'] },
      { id: 'user-content', label: '16. Contenido', title: '16. Contenido del usuario, titularidad y licencia limitada para operar la plataforma', body: ['Conservas titularidad de tu contenido y otorgas a Ownward una licencia limitada para alojar, procesar, mostrar y transmitirlo para operar, asegurar y dar soporte al servicio.'] },
      { id: 'public-v-private', label: '17. Público vs privado', title: '17. Publicaciones públicas vs contenido privado de trabajo', body: ['Las publicaciones publicadas son públicas. Borradores y contenido privado dependen de controles de acceso, pero participantes autorizados pueden conservar copias.'] },
      { id: 'third-party-data', label: '18. Datos de terceros', title: '18. Datos de terceros y clientes cargados por usuarios', body: ['Debes tener autoridad legal para subir datos de otras personas y redactar identificadores sensibles innecesarios.'] },
      { id: 'prohibited', label: '19. Conducta prohibida', title: '19. Conducta prohibida y datos restringidos', bullets: ['Prohibidas conductas ilegales, fraudulentas, infractoras o que dañen la seguridad.', 'No subas contraseñas, secretos de autenticación, datos completos de tarjeta o banco, números de seguro social o ID gubernamental completos salvo necesidad estricta y manejo legal.'] },
      { id: 'ip', label: '20. Propiedad intelectual', title: '20. Propiedad intelectual', body: ['El software, marca y contenido de Ownward están protegidos por leyes de propiedad intelectual. Estos Términos no transfieren titularidad al usuario.'] },
      { id: 'third-party-services', label: '21. Proveedores', title: '21. Servicios de terceros (Stripe, Supabase, Vercel)', bullets: ['Supabase soporta autenticación, base de datos y almacenamiento de archivos.', 'Stripe soporta checkout, suscripciones, cobros y registros de facturación.', 'Vercel soporta hosting y analítica controlada por consentimiento.'] },
      { id: 'availability', label: '22. Disponibilidad', title: '22. Disponibilidad del servicio, funciones beta, cambios y descontinuación', body: ['El servicio puede cambiar, interrumpirse o descontinuarse. Funciones beta/preview pueden ser inestables o limitadas.'] },
      { id: 'suspension', label: '23. Suspensión', title: '23. Suspensión, terminación, cancelación y consecuencias de datos', body: ['Podemos suspender o terminar cuentas por abuso, seguridad, cumplimiento legal o falta de pago. Puedes cancelar según tu plan.'] },
      { id: 'warranty', label: '24. Garantías', title: '24. Descargo de garantías', body: ['El servicio se ofrece “tal cual” y “según disponibilidad”. Ownward no garantiza exactitud de publicaciones, identidades, documentos, valoraciones, financiamiento, resultados de transacción ni disponibilidad continua.'] },
      { id: 'liability', label: '25. Responsabilidad', title: '25. Limitación razonable de responsabilidad', body: ['En la medida permitida por ley, Ownward no responde por daños indirectos, incidentales, especiales, consecuentes o punitivos derivados del uso del servicio.'] },
      { id: 'indemnity', label: '26. Indemnización', title: '26. Indemnización', body: ['Aceptas defender e indemnizar a Ownward por reclamos derivados de tu contenido, conducta, incumplimientos legales o de estos Términos.'] },
      { id: 'law', label: '27. Ley aplicable', title: '27. Ley aplicable y jurisdicción', body: ['Aplica la ley de Texas, sujeta a normas imperativas de consumo. Jurisdicción: tribunales estatales del condado Travis, Texas, o U.S. District Court for the Western District of Texas, Austin Division. No se impone arbitraje obligatorio ni renuncia a acciones colectivas.'] },
      { id: 'changes', label: '28. Cambios', title: '28. Cambios a los Términos y aviso de cambios materiales', body: ['Podemos actualizar estos Términos. Cambios materiales pueden requerir nueva aceptación afirmativa para seguir usando herramientas autenticadas. Cualquier futura comisión por transacción/referido/éxito requiere divulgación y aceptación separadas antes del cobro.'] },
      { id: 'contact', label: '29. Contacto', title: '29. Información de contacto', body: [`Contacto: ${LEGAL_OPERATOR.email}.`] },
    ],
  },
};

export const PRIVACY_CONTENT: Record<LegalLocale, { badge: string; title: string; sections: LegalSection[] }> = {
  en: {
    badge: 'Privacy Policy',
    title: 'Ownward Hub Privacy Policy',
    sections: [
      { id: 'overview', label: '1. Overview', title: '1. Controller, Scope, and 18+ Audience', body: [`${LEGAL_OPERATOR.name} operates ${LEGAL_OPERATOR.brand}. This policy covers account and service use across Ownward websites/apps. Services are intended for adults 18+.`] },
      { id: 'data-categories', label: '2. Data Categories', title: '2. Categories of Data We Process', bullets: ['Account/authentication data, profile details, and business identity records.', 'Workspace and listing data (public listings and private drafts).', 'Bookkeeping records (revenue, expenses, invoices, receipts, categories, notes).', 'Valuation inputs, adjustments, estimates, scenarios, confidence scores, and report snapshots.', 'Business-health and sale-readiness responses, evidence, and generated recommendations.', 'CRM leads/contacts, activities, revenue records, and pipeline opportunities/offers.', 'Messages, blocks, reports, and conversation metadata.', 'Deal-room invitations, members, files, requests, checklist/activity events, access/download events, IP/user-agent logs where captured by service infrastructure.', 'Support requests, Academy progress (optional local), planner progress (optional local), and community pulse submissions with optional name/email.', 'Subscription, Stripe customer IDs, payment status, and transaction/billing records.', 'Device/browser/log/diagnostic analytics data and generated inferences from user-provided business information.'] },
      { id: 'sources', label: '3. Sources', title: '3. Categories of Sources', bullets: ['Directly from you.', 'From collaborators, buyers, sellers, and deal-room participants you invite or interact with.', 'Automatically from browser/device/service usage.', 'From providers such as Stripe, Supabase, and Vercel.', 'From other users who communicate or transact with you.'] },
      { id: 'purposes', label: '4. Purposes', title: '4. Purposes and Legal Bases', bullets: ['Provide, secure, maintain, and improve services (contract/performance and legitimate interests).', 'Authenticate users and prevent abuse/fraud/security threats (legitimate interests and legal obligations).', 'Process subscriptions, billing, and support operations (contract and legal obligations).', 'Generate informational scores, valuations, recommendations, and workflow insights (contract and legitimate interests).', 'Respect consent choices for optional analytics/functionality processing (consent).'] },
      { id: 'sharing', label: '5. Sharing', title: '5. Disclosures and Recipients', bullets: ['Supabase (auth, database, storage).', 'Stripe (checkout, subscriptions, payment processing, billing records).', 'Vercel (hosting and consent-controlled web analytics).', 'Google Analytics 4 (consent-controlled web analytics with advertising and personalization disabled).', 'Advisors, authorities, or counterparties where required by law, legal process, abuse/security response, or corporate transaction.'] },
      { id: 'public-private', label: '6. Visibility', title: '6. Public vs Private Content and Participant Access', body: ['Published listing fields are publicly visible. Draft/private workspace content is access-controlled. Users, collaborators, buyers, sellers, and deal-room participants with granted access may view/download/retain data shared with them. Ownward may access content where reasonably necessary for support, security, abuse prevention, legal compliance, and operations.'] },
      { id: 'sensitive', label: '7. Sensitive Data Guidance', title: '7. Upload Authority and Sensitive Data Guidance', bullets: ['Upload data about others only when you have lawful authority.', 'Redact Social Security numbers, government ID numbers, full bank details, card details, passwords, authentication credentials, and unnecessary sensitive data before upload.', 'Stripe handles payment-card details; Ownward should not be used to store full card numbers.'] },
      { id: 'consent-storage', label: '8. Cookies & Storage', title: '8. Cookies, Local Storage, and Consent Controls', bullets: ['Necessary: Supabase auth/session cookies, security/session operations, NEXT_LOCALE preference cookie, and consent-state storage.', 'Functionality consent gates optional local persistence keys: ownward_academy_progress_v1, ownward_start_business_plan_v1, ownward_visitor_token.', 'Analytics consent gates both Vercel Web Analytics and Google Analytics 4 loading/event flow.', 'Ownward analytics sanitization strips fragments, keeps only allowed campaign parameters, and redacts known private dynamic IDs/tokens before events are sent.', 'Google Analytics consent mode is configured with security storage granted, analytics storage denied by default, and advertising/personalization storage denied.', 'Google explains partner-site data processing here: https://policies.google.com/technologies/partner-sites', 'Ownward does not currently sell personal data or share for cross-context behavioral advertising/targeted advertising based on current implementation.'] },
      { id: 'automated', label: '9. Automated Outputs', title: '9. Automated Outputs', body: ['Valuations, scores, and recommendations are informational workflow outputs and are not used as significant automated eligibility decisions for credit, employment, housing, insurance, or similar legal effects.'] },
      { id: 'retention', label: '10. Retention', title: '10. Retention Criteria', body: ['Retention depends on account status, feature usage, support/security needs, billing/dispute/fraud prevention, legal obligations, and enforcement needs. Fixed retention timers are not universally implemented across all records.'] },
      { id: 'security', label: '11. Security', title: '11. Security and International Processing', body: ['Ownward uses technical/organizational safeguards and provider controls, but no system is perfectly secure. Processing may occur in jurisdictions outside your own through infrastructure providers and service operations.'] },
      { id: 'rights', label: '12. Rights', title: '12. Privacy Rights, Verification, and Appeals', bullets: ['You may request access, correction, deletion, export, restriction, or objection where applicable law grants those rights.', `Submit requests to ${LEGAL_OPERATOR.email}; we may verify identity before fulfilling requests.`, 'If we deny or limit a request, you may reply to request reconsideration/appeal and we will review according to applicable law.', 'We may retain data needed for billing, disputes, fraud prevention, security, legal obligations, or terms enforcement.'] },
      { id: 'changes-contact', label: '13. Changes and Contact', title: '13. Policy Changes and Contact', body: ['We may update this policy. Material updates may require acknowledgment/notice in-product. Optional new processing still requires separate consent when applicable.', `Contact: ${LEGAL_OPERATOR.email}. Correspondence address: ${LEGAL_OPERATOR.address} (mail only, not walk-in).`] },
    ],
  },
  es: {
    badge: 'Política de privacidad',
    title: 'Política de privacidad de Ownward Hub',
    sections: [
      { id: 'overview', label: '1. Resumen', title: '1. Responsable, alcance y público 18+', body: [`${LEGAL_OPERATOR.name} opera ${LEGAL_OPERATOR.brand}. Esta política cubre el uso de cuentas y servicios de Ownward. El servicio está dirigido a adultos de 18+.`] },
      { id: 'data-categories', label: '2. Categorías de datos', title: '2. Categorías de datos que tratamos', bullets: ['Datos de cuenta/autenticación, perfil e identidad empresarial.', 'Datos de espacios de trabajo y publicaciones (públicas y borradores privados).', 'Registros contables (ingresos, gastos, facturas, recibos, categorías, notas).', 'Entradas de valoración, ajustes, estimaciones, escenarios, puntajes y reportes.', 'Datos de salud del negocio y preparación para venta, evidencia y recomendaciones.', 'Leads/contactos CRM, actividades, ingresos por cliente y pipeline/ofertas.', 'Mensajes, bloqueos, reportes y metadatos de conversación.', 'Invitaciones de deal room, miembros, archivos, solicitudes, checklist/actividad y eventos de acceso/descarga, IP/user-agent cuando los registre la infraestructura.', 'Solicitudes de soporte, progreso de Academy (local opcional), progreso del plan de inicio (local opcional) y respuestas de Community Pulse con nombre/correo opcionales.', 'Registros de suscripción, IDs de cliente Stripe, estado de pago y facturación.', 'Datos de dispositivo/navegador/log/diagnóstico y deducciones generadas a partir de información provista por usuarios.'] },
      { id: 'sources', label: '3. Fuentes', title: '3. Categorías de fuentes', bullets: ['Directamente de ti.', 'De colaboradores, compradores, vendedores y participantes de deal room con quienes interactúas.', 'Automáticamente desde navegador/dispositivo/uso del servicio.', 'De proveedores como Stripe, Supabase y Vercel.', 'De otros usuarios que se comunican o transaccionan contigo.'] },
      { id: 'purposes', label: '4. Finalidades', title: '4. Finalidades y bases legales', bullets: ['Prestar, asegurar, mantener y mejorar el servicio (contrato/interés legítimo).', 'Autenticar, prevenir abuso/fraude y responder incidentes de seguridad (interés legítimo/obligación legal).', 'Gestionar suscripciones, cobros y soporte (contrato/obligación legal).', 'Generar puntajes, valoraciones, recomendaciones e insights informativos (contrato/interés legítimo).', 'Respetar elecciones de consentimiento para procesamiento opcional (consentimiento).'] },
      { id: 'sharing', label: '5. Compartición', title: '5. Divulgación y destinatarios', bullets: ['Supabase (autenticación, base de datos y almacenamiento).', 'Stripe (checkout, suscripciones, pagos y registros de facturación).', 'Vercel (hosting y analítica web controlada por consentimiento).', 'Google Analytics 4 (analítica web controlada por consentimiento con publicidad y personalización desactivadas).', 'Asesores, autoridades o partes de transacciones corporativas cuando aplique por ley, seguridad o cumplimiento.'] },
      { id: 'public-private', label: '6. Visibilidad', title: '6. Contenido público vs privado y acceso de participantes', body: ['Los campos de publicaciones publicadas son públicos. El contenido privado tiene controles de acceso. Usuarios/colaboradores/compradores/vendedores/participantes autorizados pueden ver/descargar/conservar información compartida. Ownward puede acceder cuando sea razonablemente necesario para soporte, seguridad, prevención de abuso, cumplimiento legal y operación.'] },
      { id: 'sensitive', label: '7. Datos sensibles', title: '7. Autoridad para subir datos y guía sobre datos sensibles', bullets: ['Sube datos de terceros solo con autoridad legal.', 'Redacta números de seguro social, identificaciones gubernamentales, datos bancarios completos, datos completos de tarjeta, contraseñas y credenciales de autenticación antes de subir documentos.', 'Stripe procesa datos de tarjeta; Ownward no debe usarse para almacenar números completos de tarjeta.'] },
      { id: 'consent-storage', label: '8. Cookies y almacenamiento', title: '8. Cookies, localStorage y controles de consentimiento', bullets: ['Necesario: cookies de sesión/autenticación Supabase, operaciones de seguridad/sesión, cookie NEXT_LOCALE y almacenamiento de consentimiento.', 'Funcionalidad controla claves locales opcionales: ownward_academy_progress_v1, ownward_start_business_plan_v1, ownward_visitor_token.', 'Analítica controla la carga y envío de Vercel Web Analytics y Google Analytics 4.', 'El sanitizador elimina fragmentos, conserva solo parámetros de campaña permitidos y redacciona IDs/tokens privados dinámicos conocidos antes de enviar eventos.', 'El modo de consentimiento de Google Analytics mantiene security_storage activo, analytics_storage denegado por defecto y publicidad/personalización denegadas.', 'Google explica el uso de datos en sitios asociados aquí: https://policies.google.com/technologies/partner-sites', 'Con la implementación actual, Ownward no vende datos personales ni comparte para publicidad conductual entre contextos.'] },
      { id: 'automated', label: '9. Salidas automáticas', title: '9. Salidas automáticas', body: ['Las valoraciones, puntajes y recomendaciones son informativos y no se usan como decisiones automatizadas significativas de elegibilidad para crédito, empleo, vivienda, seguros u efectos legales similares.'] },
      { id: 'retention', label: '10. Retención', title: '10. Criterios de retención', body: ['La retención depende del estado de cuenta, uso de funciones, soporte/seguridad, cobros/disputas/fraude, obligaciones legales y cumplimiento contractual. No existen tiempos fijos universales para todos los registros.'] },
      { id: 'security', label: '11. Seguridad', title: '11. Seguridad y tratamiento internacional', body: ['Ownward usa salvaguardas técnicas/organizativas y controles de proveedores, pero ningún sistema es totalmente seguro. El tratamiento puede ocurrir en jurisdicciones distintas a la tuya mediante proveedores e infraestructura.'] },
      { id: 'rights', label: '12. Derechos', title: '12. Derechos de privacidad, verificación y apelación', bullets: ['Puedes solicitar acceso, corrección, eliminación, exportación, restricción u objeción cuando la ley aplicable lo permita.', `Envía solicitudes a ${LEGAL_OPERATOR.email}; podemos verificar identidad antes de responder.`, 'Si rechazamos o limitamos una solicitud, puedes pedir revisión/apelación y la evaluaremos según la ley aplicable.', 'Podemos conservar datos necesarios para facturación, disputas, fraude, seguridad, obligaciones legales o cumplimiento de términos.'] },
      { id: 'changes-contact', label: '13. Cambios y contacto', title: '13. Cambios de política y contacto', body: ['Podemos actualizar esta política. Cambios materiales pueden requerir aviso o reconocimiento en producto. Nuevo procesamiento opcional requiere consentimiento separado cuando corresponda.', `Contacto: ${LEGAL_OPERATOR.email}. Dirección de correspondencia: ${LEGAL_OPERATOR.address} (solo correo, no atención presencial).`] },
    ],
  },
};
