#!/usr/bin/env bash
# scripts/audit-remote-branches.sh
#
# Read-only remote branch audit script.
# Generates a Markdown report of every remote branch vs origin/main.
#
# Usage:
#   bash scripts/audit-remote-branches.sh
#   npm run audit:branches
#
# Safety: this script NEVER checks out, merges, commits, pushes, or deletes branches.

set -euo pipefail

REPORT_DIR="docs"
REPORT_FILE="${REPORT_DIR}/branch-audit-$(date +%Y-%m-%d).md"
DEFAULT_BRANCH="${DEFAULT_BRANCH:-main}"
REMOTE="${REMOTE:-origin}"

# Ensure we have latest remote info (read-only fetch)
echo "Fetching remote refs (read-only)..." >&2
git fetch "${REMOTE}" --prune --tags --quiet

MAIN_SHA=$(git rev-parse "${REMOTE}/${DEFAULT_BRANCH}" 2>/dev/null || {
  echo "ERROR: Cannot resolve ${REMOTE}/${DEFAULT_BRANCH}" >&2
  exit 1
})

AUDIT_DATE=$(date +%Y-%m-%d)
HOSTNAME=$(git remote get-url "${REMOTE}" 2>/dev/null || echo "unknown")

mkdir -p "${REPORT_DIR}"

{
  echo "# Remote Branch Audit — ${AUDIT_DATE}"
  echo ""
  echo "| Field | Value |"
  echo "|---|---|"
  echo "| Remote | \`${REMOTE}\` |"
  echo "| Remote URL | \`${HOSTNAME}\` |"
  echo "| Default branch | \`${DEFAULT_BRANCH}\` |"
  echo "| Baseline SHA | \`${MAIN_SHA}\` |"
  echo "| Generated | ${AUDIT_DATE} |"
  echo ""
  echo "## Branch Summary"
  echo ""
  echo "| Branch | SHA | Ahead | Behind | Ancestor of main? | Last commit date | Last commit message |"
  echo "|---|---|---|---|---|---|---|"

  while IFS= read -r ref; do
    branch="${ref#  ${REMOTE}/}"

    # Skip HEAD and the default branch
    [[ "${branch}" == "HEAD" ]] && continue
    [[ "${branch}" == "${DEFAULT_BRANCH}" ]] && continue

    sha=$(git rev-parse "${REMOTE}/${branch}" 2>/dev/null) || continue
    short_sha="${sha:0:9}"
    ahead=$(git rev-list --count "${REMOTE}/${DEFAULT_BRANCH}..${REMOTE}/${branch}" 2>/dev/null || echo "?")
    behind=$(git rev-list --count "${REMOTE}/${branch}..${REMOTE}/${DEFAULT_BRANCH}" 2>/dev/null || echo "?")
    is_ancestor=$(git merge-base --is-ancestor "${REMOTE}/${branch}" "${REMOTE}/${DEFAULT_BRANCH}" 2>/dev/null \
      && echo "YES" || echo "NO")
    last_date=$(git log -1 --pretty="%ad" --date=short "${REMOTE}/${branch}" 2>/dev/null || echo "unknown")
    last_msg=$(git log -1 --pretty="%s" "${REMOTE}/${branch}" 2>/dev/null | head -c 80 || echo "unknown")
    # Escape pipe characters for Markdown table
    last_msg="${last_msg//|/\\|}"

    echo "| \`${branch}\` | \`${short_sha}\` | ${ahead} | ${behind} | ${is_ancestor} | ${last_date} | ${last_msg} |"
  done < <(git branch -r | grep "^  ${REMOTE}/")

  echo ""
  echo "## Branches Ahead of \`${DEFAULT_BRANCH}\` (Unique Commits)"
  echo ""
  echo "The following branches have commits not present in \`${DEFAULT_BRANCH}\`:"
  echo ""

  FOUND_AHEAD=0
  while IFS= read -r ref; do
    branch="${ref#  ${REMOTE}/}"
    [[ "${branch}" == "HEAD" ]] && continue
    [[ "${branch}" == "${DEFAULT_BRANCH}" ]] && continue

    ahead=$(git rev-list --count "${REMOTE}/${DEFAULT_BRANCH}..${REMOTE}/${branch}" 2>/dev/null || echo "0")
    [[ "${ahead}" == "0" ]] && continue

    FOUND_AHEAD=1
    sha=$(git rev-parse "${REMOTE}/${branch}" 2>/dev/null) || continue
    is_ancestor=$(git merge-base --is-ancestor "${REMOTE}/${branch}" "${REMOTE}/${DEFAULT_BRANCH}" 2>/dev/null \
      && echo "YES" || echo "NO")

    echo "### \`${branch}\`"
    echo ""
    echo "- **SHA**: \`${sha}\`"
    echo "- **Ahead**: ${ahead} commit(s)"
    echo "- **Ancestor of main**: ${is_ancestor}"
    echo ""
    echo "**Unique commits (git cherry):**"
    echo ""
    echo "\`\`\`"
    git cherry "${REMOTE}/${DEFAULT_BRANCH}" "${REMOTE}/${branch}" 2>/dev/null | head -20 || true
    echo "\`\`\`"
    echo ""
    echo "**Diff stat vs \`${DEFAULT_BRANCH}\`:**"
    echo ""
    echo "\`\`\`"
    git diff --stat "${REMOTE}/${DEFAULT_BRANCH}...${REMOTE}/${branch}" 2>/dev/null | tail -5 || true
    echo "\`\`\`"
    echo ""
  done < <(git branch -r | grep "^  ${REMOTE}/")

  if [[ "${FOUND_AHEAD}" == "0" ]]; then
    echo "_No branches with unique commits found._"
    echo ""
  fi

  echo "---"
  echo ""
  echo "_This report was generated by \`scripts/audit-remote-branches.sh\`._"
  echo "_It is read-only: no branches were checked out, merged, committed, pushed, or deleted._"
} > "${REPORT_FILE}"

echo "Branch audit report written to: ${REPORT_FILE}" >&2
echo "${REPORT_FILE}"
